# SPDX-FileCopyrightText: 2023 Mercedes-Benz Tech Innovation GmbH
#
# SPDX-License-Identifier: MIT

FROM scratch
COPY disclosure-cli /usr/bin/disclosure-cli
COPY Third_Party_Notices.txt Third_Party_Notices.txt
ENTRYPOINT ["/usr/bin/disclosure-cli"]
