# SPDX-FileCopyrightText: 2023 Mercedes-Benz Tech Innovation GmbH
#
# SPDX-License-Identifier: MIT

name: Run tests
on:
  push:
    branches:
      - main
      - action_test
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ secrets.CONFIG}}
      SBOM: ${{ secrets.SBOM}}
      HOST: ${{ secrets.DISCO_HOST}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.23'
      - name: Create config and sbom file
        run: |
          echo $CONFIG | base64 -d > conf.yml
          echo $SBOM | base64 -d > sbom.json
      - name: Run tests
        run: |
          go test -v ./... 
